name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macOS-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # 设置 Xcode 16.2 作为默认 Xcode 版本
      - name: Set Xcode 16.2
        run: |
          sudo xcode-select -s /Applications/Xcode_16.2.app/Contents/Developer
          xcodebuild -version

      # 构建项目，确保项目文件存在并正确构建
      - name: Build the app
        run: |
          # 确保指定的 .xcodeproj 文件路径正确
          xcodebuild build -scheme 'MyApp' -configuration Debug -project 'MyApp.xcodeproj' -destination 'generic/platform=iOS Simulator' CONFIGURATION_BUILD_DIR=$PWD/build

      # 启动应用并执行基本的测试
      - name: Run tests
        run: |
          xcodebuild test -scheme 'MyApp' -configuration Debug -project 'MyApp.xcodeproj' -destination 'platform=iOS Simulator,name=iPhone 13'
